const tones = {
  正常运营: 'success',
  '정상 운영': 'success',
  正常: 'success',
  完成: 'success',
  승인: 'success',
  '답변 완료': 'success',
  판매중: 'success',
  销售中: 'success',
  구매확정: 'success',
  增长: 'success',
  정상: 'success',
  '정상 운영': 'success',
  使用中: 'success',
  완료: 'success',
  성공: 'success',
  '已处理': 'success',

  处理中: 'info',
  심사중: 'info',
  처리중: 'info',
  배송중: 'info',
  待发货: 'info',
  '제출 완료': 'info',
  사용중: 'info',
  대기중: 'info',
  提交中: 'info',
  审核中: 'info',

  警告: 'warning',
  波动: 'warning',
  '추가 자료 요청': 'warning',
  '환불 요청': 'warning',
  '교환 요청': 'warning',
  审核中: 'warning',
  申诉中: 'warning',
  重要: 'warning',
  중요: 'warning',
  '확인 필요': 'warning',
  '인증 필요': 'warning',
  '점검 필요': 'warning',
  '쿠키 만료': 'warning',
  경고: 'warning',
  '申诉截止提醒': 'warning',

  风险: 'danger',
  판매중지: 'danger',
  정산보류: 'danger',
  반려: 'danger',
  紧急: 'danger',
  긴급: 'danger',
  取消退款: 'danger',
  预警: 'danger',
  위험: 'danger',
  '위험 감지': 'danger',
  차단됨: 'danger',
  '로그인 제한': 'danger',
  '수신 실패': 'danger',
  사용중지: 'danger',
  실패: 'danger',

  待处理: 'pending',
  '문의 대기': 'pending',
  '자료 준비중': 'pending',
  '제출 대기': 'pending',
  草稿: 'pending',
  一般: 'neutral',
  일반: 'neutral',
  기타: 'neutral',
  未知: 'neutral',
  未绑定: 'neutral',
  '未处理': 'pending',
  只读: 'neutral',
};

export default function StatusBadge({ value }) {
  return <span className={`status-badge ${tones[value] || 'neutral'}`}><i />{value}</span>;
}
